---
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args: ['--max-warnings=0']

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest version available
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.6
    hooks:
      - id: autopep8
        files: \.py$

